[package]
name = "fuse-rs"
version = "0.1.0"
edition = "2024"
authors = ["Md Sadique Inam <md.sadique32@gmail.com>"]

[dependencies]
serde_json = "1.0.140"
unicode-normalization = "0.1.24"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
merge = "0.2.0"